[project]
name = "conda-channel-mirrors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "httpx==0.28.1",
  "py-rattler==0.12.0",
]

[tool.black]
preview = true
unstable = true
