name: release

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "45 13 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  mirror:
    name: Mirror Packages
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: prefix-dev/rattler-build
          tag: "v0.41.0"

      - run: uv sync --locked
      - run: python main.py
        env:
          ANACONDA_API_KEY: "${{ secrets.ANACONDA_API_KEY }}"
